packages:
  - "apps/*"
  - "packages/*"
  - "stacks/*/**"
  - "examples/*"

catalog:
  "@pulumi/aws": ^7.6.0
  "@pulumi/pulumi": ^3.192.0
  "@pulumi/command": ^1.1.0
  "@types/node": ^24.3.0
  typescript: ^5.9.2
  "@types/archiver": ^6.0.3
  "@types/mime-types": ^3.0.1
  "mime-types": ^3.0.1
  archiver: ^7.0.1
  globby: ^14.0.2
  react: ^19.1.1
  "react-dom": ^19.1.1
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
  "@react-router/dev": ^7.8.2
  "@react-router/node": ^7.8.2
  "@sveltejs/kit": ^2.37.0
  svelte: ^5.38.6
  eslint: ^9.34.0
  "@eslint/js": ^9.34.0
  "eslint-config-prettier": ^10.1.8
  "eslint-plugin-turbo": ^2.5.6
  "typescript-eslint": ^8.41.0
  next: ^15.5.2
  "@opennextjs/aws": ^3.7.5
  vite: ^7.1.3
  "@tailwindcss/cli": ^4.1.12
  "@tailwindcss/postcss": ^4.1.12
  "zod": "^4.1.5"
